### ISSUE TITLE
Not enough 卐

### ISSUE THREAD

**Issue by moddedgear** [StrangeParadox/lambda-discord-bot#2]
There are not enough of "卐" throughout the code, please add more of them, thanks]

yours sincezly
so anyways I started blasting 卐卐卐

**Comment by StrangeParadox** [comment]
ease

**Comment by moddedgear** [comment]
> ease
> […](#)
> On Mar 17 2021, at 12:57 am, MODDEDGEAR ***@***.***> wrote: There are not enough of "卐" throughout the code, please add more of them, thanks] yours sincezly so anyways I started blasting 卐卐卐 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub ***@***.***/0?redirect=https%3A%2F%2Fgithub.com%2FStrangeParadox%2Flambda-discord-bot%2Fissues%2F2&recipient=cmVwbHkrQU9UNVVZNDZHTFdUTEtOVDYyNDQ0MzU2TFUyT1pFVkJOSEhEREtaNUZJQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOT5UY3LLJUWSJCLSVXJWUTTD746ZANCNFSM4ZJTGMBA&recipient=cmVwbHkrQU9UNVVZNDZHTFdUTEtOVDYyNDQ0MzU2TFUyT1pFVkJOSEhEREtaNUZJQHJlcGx5LmdpdGh1Yi5jb20%3D).

卐卐卐卐卐 ez ez ez ez ease ease ease
![image0](https://user-images.githubusercontent.com/29043147/111398692-d9710080-86bb-11eb-9f08-4035c3fe3a88.jpg)

**Comment by StrangeParadox** [comment]
I like this photo. Thanks. I will look into this problem.
Mines truely,
Big bag of Salt
