### ISSUE TITLE
Black lives matter

### ISSUE THREAD

**Issue by moddedgear** [StrangeParadox/lambda-discord-bot#3]
![image0](https://user-images.githubusercontent.com/29043147/111398723-ea217680-86bb-11eb-9cc1-8fd979b9d86b.jpg)

This pictures tells me different... 卐卐卐

**Comment by StrangeParadox** [comment]
!matter

**Comment by moddedgear** [comment]
> !matter

 Is that going to be a command?

**Comment by StrangeParadox** [comment]
> > !matter
> 
> Is that going to be a command?

No. Waste of space, just like the photo atop.

**Comment by moddedgear** [comment]
> > > !matter
> > 
> > 
> > Is that going to be a command?
> 
> No. Waste of space, just like the photo atop.


https://user-images.githubusercontent.com/29043147/111398898-1b9a4200-86bc-11eb-95b3-059fd9320fab.mp4

**Comment by StrangeParadox** [comment]
> > > > !matter
> > > 
> > > 
> > > Is that going to be a command?
> > 
> > 
> > No. Waste of space, just like the photo atop.
> 
>  video0-3.mp4

eased on

**Comment by moddedgear** [comment]
![Orange juice guy](https://user-images.githubusercontent.com/29043147/111398928-2e147b80-86bc-11eb-84fd-3c266be280ed.jpg)
![IMG_20200711_105206_199](https://user-images.githubusercontent.com/29043147/111398933-3076d580-86bc-11eb-9556-e4fae13943e2.jpg)
![image0](https://user-images.githubusercontent.com/29043147/111398934-32409900-86bc-11eb-9639-7929eff6e9b0.jpg)

https://user-images.githubusercontent.com/29043147/111399101-919ea900-86bc-11eb-9e7f-8d2d52a76b00.mp4
